# Build the application from source
FROM golang:1.22.3 AS build-stage
  WORKDIR /server

  COPY go.mod go.sum ./
  RUN go mod download

  COPY . .

  RUN CGO_ENABLED=0 GOOS=linux go build -o /server ./cmd/server/main.go

# Run the tests in the container
FROM build-stage AS run-test-stage
  RUN go test -v ./...

# Deploy the application binary into a lean image
FROM scratch AS build-release-stage
  WORKDIR /

  COPY --from=build-stage /server /server

  EXPOSE 8080

  ENTRYPOINT ["/server"]
