services:
  meal-planner.db:
    env_file:
      - .env
    image: ${DB_VER}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql_db_data:/var/lib/mysql
    ports:
      - "33060:3306"

    healthcheck:
      test: "mysql -uroot -p${DB_PASS} ${DB_NAME} -e 'select 1'"
      timeout: 20s
      interval: 10s
      retries: 5

  meal-planner.db.migrations:
    env_file:
      - .env
    depends_on:
      meal-planner.db:
        condition: service_healthy
    image: meal-planner.db.migrations
    build:
      context: ../db/
      dockerfile: Dockerfile
      args:
        - DB_PASS=${DB_PASS}
        - DB_NAME=${DB_NAME}
        - DB_PORT=${DB_PORT}
    command: "'mysql://root:secret@tcp(meal-planner.db:3306)/meal_planner_app_server_db' up"

volumes:
  mysql_db_data:
