services:
  meal-planner.db:
    env_file:
      - .env
    image: ${DB_VER}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql_db_data:/var/lib/mysql
    ports:
      - "3306:3306"

    healthcheck:
      test: "mysql -uroot -p${DB_PASS} ${DB_NAME} -e 'select 1'"
      timeout: 20s
      interval: 10s
      retries: 5

  server:
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    restart: on-failure
    volumes:
      - .:/go/src/server
    ports: 
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: meal-planner.db
      DB_USER: root
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    links:
      - meal-planner.db
    depends_on:
      - meal-planner.db

volumes:
  mysql_db_data:
