name: PR Checks

on: pull_request

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.3"
      - name: Get dependencies
        run: go mod tidy
      - name: Test
        run: go test -v ./...
